---
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6
  ruby: circleci/ruby@2.1.0

jobs:
  rerun-true:
    docker:
      - image: cimg/ruby:2.7.4
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check chrome install
      - ruby/install-deps:
          key: gem-2
      - ruby/rspec-test:
          include: "spec/**/*_spec.rb"
          order: random
      - store_test_results:
          path: ~/rspec/rspec.xml

  rerun-false:
    docker:
      - image: cimg/ruby:2.7.4-browsers
    parallelism: 4
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check chrome install
      - ruby/install-deps:
          key: gem-2
      - ruby/rspec-test:
          include: "spec/**/*_spec.rb"
          rerun-fail: false
      - store_test_results:
          path: ~/rspec/rspec.xml
workflows:
  test_build:
    jobs:
      - rerun-true
      - rerun-false
